# -*- coding: utf-8 -*-
"""Dios 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibM3Q_OC5poJpKmVoWkjTDgY3mb-NOMp
"""

# Commented out IPython magic to ensure Python compatibility.
!mkdir Laboratorio-2
# %cd Laboratorio-2

!pip install pandas folium

!ls

!python Grafos.py